#!/bin/bash

### I have one file which 10 records which is having names like Venkat, Ibrahim, Sooraj which are having salary
between 10k - 30k, I need to see who are having the salary greater than 10k

ENO  EMPLOYEENAME EMPSALARY
1    VENKATESH    150000
2    SOORAJ       200000
3    Ibrahim      300000
If salary > 10000
 print ("")